version: '3'
services:
  flask:
    build:
      context: ./
    container_name: chat_bot_server
    tty: true
    stdin_open: true
    ports:
      - "1234:1234"

    volumes:
      - ./web:/app/
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    env_file:
      - web/.env
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: flask:1234
    depends_on:
      - flask
